stages:
  prepare_data:
    cmd: python scripts/prepare_data.py
    deps:
      - scripts/prepare_data.py
    outs:
      - data/processed/squat_form/
      - data/splits/
      - data/processed/squat_form/subject_metadata.csv # Added subject metadata to DVC tracking
